database/models/cliente.py
from peewee import Model, CharField, DateTimeField
from database.database import db
import datetime


class Cliente(Model):
    nome = CharField()
    email= CharField()
    data_registro = DateTimeField(default=datetime.datetime.now)
    
    class Meta:
        database =   db

main.py
from flask import Flask
from configuration import configure_all

app = Flask(__name__)



app.config['SEND_FILE_MAX_AGE_DEFAULT'] = 0
app.static_folder = 'static'


configure_all(app)


app.run(debug=True)

routes/cliente.py
from flask import Blueprint,render_template, request
from database.cliente import CLIENTES
from database.models.cliente import Cliente



cliente_route = Blueprint('cliente', __name__)
"""
    rota do clliente
    
    - /clientes/ GET- listar os clientes
    - /clientes/ POST- insere o cliente no server
    - /clientes/new GET- renderiza o formulario para criar um cliente
    -/clientes/<id> GET- obtem os dados do cliente
    - /cliente/<id>/edit GET- renderiza um formulario para alterar os dados de um cliente
    - /cliente/<id>/update PUT- atualiza os dados do cliente 
    - /cliente/<id>/delete DELETE - deleta o registro do usuário    
"""


@cliente_route.route('/')
def lista_clientes():
    '''listar clientes'''
    clientes = Cliente.select()
    return render_template('lista_clientes.html',clientes = clientes)



@cliente_route.route('/', methods=['POST'])
def inserir_cliente():
    '''insere os dados do cliente no bnaco de dados'''
    data = request.json
    
    novo_usuario = Cliente.create(
        nome =data['nome'],
        email =data['email'],
    )
    return render_template('item_cliente.html', cliente=novo_usuario)



@cliente_route.route('/new')
def form_cliente():
    '''formulatio pra cadastraar um cliente'''
    return render_template('form_clientes.html')



@cliente_route.route('/<int:cliente_id>')
def detalhe_cliente(cliente_id):
    '''exibe os detalhes do cliente'''
    
    cliente = Cliente.get_by_id(cliente_id)
    return render_template('detalhe_cliente.html', cliente=cliente)



@cliente_route.route('/<int:cliente_id>/edit')
def form_edit_cliente(cliente_id):
    '''formulario pra editar os dados do cliente'''
    
    cliente = None
    
    cliente = Cliente.get_by_id(cliente_id)
    
    return render_template('form_clientes.html', cliente=cliente)



@cliente_route.route('/<int:cliente_id>/update', methods=['PUT'])
def update_cliente(cliente_id):
    data = request.json
    cliente_editado = Cliente.get_by_id(cliente_id)
    cliente_editado.nome = data['nome']
    cliente_editado.email = data['email']
    cliente_editado.save()
            
    return render_template('item_cliente.html', cliente=cliente_editado)         


   
@cliente_route.route('/<int:cliente_id>/delete', methods=['DELETE'])
def delete_clientes(cliente_id):
    '''deleta os dados do cliente'''
    cliente = Cliente.get_by_id(cliente_id)
    cliente.delete_instance()
    return {'deleted' : 'ok'}

routes/home.py
from flask import Blueprint,render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')

def home():
    return render_template('index.html')


templates/detalhe_cliente.html
<ul>
    <li>ID: {{cliente.id}}</li>
    <li>NOME: {{cliente.nome}}</li>
    <li>EMAIL: {{cliente.email}}</li>
</ul>

templates/form_clientes.html
<form class="c-form"
    {% if  cliente%}
        action="{{url_for('cliente.update_cliente', cliente_id= cliente.id)}}" 
    {% else %}
        action="{{url_for('cliente.inserir_cliente')}}" 
    
    {% endif %}
    method='{% if cliente %}PUT{%else%}POST{% endif %}'

    {% if cliente  %}
        c-swap="#cliente-{{cliente.id}}"
    {% else %}
        c-append="#lista-clientes"
    {% endif %}
    
    c-reload-container="true"
    >

    
    <div class="mb-3">
      <label class="form-label">Nome</label>
      <input type="text" class="form-control" name="nome" {% if cliente %} value='{{ cliente.nome }}'{% endif %}>

    </div>

    
    <div class="mb-3">
      <label class="form-label">Email </label>
      <input type="text" class="form-control" name="email" {% if  cliente%}value='{{cliente.email}}'{%endif %}>
    </div>
    
 
    </div>
    <button type="submit" class="btn btn-primary">
        {% if cliente %}Salvar{% else %}Criar{% endif %}
    
    </button>
  </form>

templates/index.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bootstrap demo</title>

  <link rel="stylesheet" href="{{ url_for('static', filename='css/app_v2.css') }}">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
  <h1 class="text-center">Gestão de clientes</h1>
  <div class="container">

    <!-- Formulario de criacao de clientes -->
    <div id="form-cliente" c-container="{{url_for('cliente.form_cliente')}}"></div>
    <!-- Lista de clientes -->
    <hr>
    <h3>Lista de clientes</h3>

    <div  c-container="{{url_for('cliente.lista_clientes')}}"></div>

  </div>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id="exibir-cliente"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
        </div>
      </div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>

  <script src="{{ url_for('static', filename='js/cru_v2.js') }}"></script>
</body>

</html>

templates/item_cliente.html
<tr id="cliente-{{cliente.id}}">
    <th scope="row">{{cliente.id}}</th>
    <td>{{cliente.nome}}</td>
    <td>{{cliente.email}}</td>
    <td>{{cliente.data_registro}}</td>
    <td>
        <button class='btn btn-secondary' 
        c-get="{{url_for('cliente.detalhe_cliente',   cliente_id =cliente.id)    }}" 
        c-target="#exibir-cliente" 
        data-bs-toggle="modal" data-bs-target="#exampleModal">
            Ver
    </button>
    <button class="btn btn-primary" 
    c-get="{{ url_for('cliente.form_edit_cliente', cliente_id=cliente.id) }}"
    c-target="#form-cliente">
        Editar
</button>

        <button class='btn btn-danger'
         c-delete="{{url_for('cliente.delete_clientes', cliente_id=cliente.id)}}"
         c-remove-closest="tr">Delete</button>
    </td>
  </tr>

templates/lista_clientes.html
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Data de criação</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody id="lista-clientes">
        {% for cliente in clientes  %}
          {% include "item_cliente.html" %}
        {% endfor %}

     
    </tbody>
  </table>